<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.11.0" NoWarn="NU1901;NU1902;NU1903" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.2" NoWarn="NU1901;NU1902;NU1903" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" NoWarn="NU1901;NU1902;NU1903" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="5.2.1" NoWarn="NU1901;NU1902;NU1903" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="6.0.0" NoWarn="NU1901;NU1902;NU1903" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.60.1" NoWarn="NU1901;NU1902;NU1903" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.5.0" NoWarn="NU1901;NU1902;NU1903" />
    <PackageReference Include="SixLabors.Fonts" Version="2.0.1" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" NoWarn="NU1901;NU1902;NU1903" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="fonts\Caveat\static\Caveat-Regular.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
